name: Run Tests

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set BASE_URL environment variable
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV

      - name: Set TELEGRAM_BOT_TOKEN environment variable
        run: echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV

      - name: Create temporary keys_de_bridge.json
        run: echo '${{ secrets.KEYS_DE_BRIDGE }}' > keys_de_bridge.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and generate Allure report
        id: test-results
        run: |
          python -m pytest -n=2 ./tests/api_tests/tests_de_bridge.py --alluredir=./docs/allure-results
          allure generate ./docs/allure-results -o ./docs/allure-report --clean


      - name: Send Test Results via Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TOTAL_TESTS: ${{ env.TOTAL_TESTS }}
          PASSED_TESTS: ${{ env.PASSED_TESTS }}
          FAILED_TESTS: ${{ env.FAILED_TESTS }}
          SKIPPED_TESTS: ${{ env.SKIPPED_TESTS }}
        run: python telegram_bot.py
