name: Run Tests

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set BASE_URL environment variable
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV

      - name: Create temporary keys_de_bridge.json
        run: echo '${{ secrets.KEYS_DE_BRIDGE }}' > keys_de_bridge.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        id: test-results
        run: |
          python -m pytest -n=2 ./tests/api_tests/tests_de_bridge.py | tee test_results.txt
          echo "TOTAL_TESTS=$(cat test_results.txt | grep -oP '(\d+) total')" >> $GITHUB_ENV
          echo "PASSED_TESTS=$(cat test_results.txt | grep -oP '(\d+) passed')" >> $GITHUB_ENV
          echo "FAILED_TESTS=$(cat test_results.txt | grep -oP '(\d+) failed')" >> $GITHUB_ENV
          echo "SKIPPED_TESTS=$(cat test_results.txt | grep -oP '(\d+) skipped')" >> $GITHUB_ENV

      - name: Send Test Results via Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TOTAL_TESTS: ${{ env.TOTAL_TESTS }}
          PASSED_TESTS: ${{ env.PASSED_TESTS }}
          FAILED_TESTS: ${{ env.FAILED_TESTS }}
          SKIPPED_TESTS: ${{ env.SKIPPED_TESTS }}
        run: python telegram_bot.py
