name: Run Tests

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create temporary keys_de_bridge.json
        run: printf '%s' "${{ secrets.KEYS_DE_BRIDGE }}" > keys_de_bridge.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug1
        run: pwd

      - name: Debug2
        run: ls

      - name: Run tests
        run: |
          python -m pytest -n=1 ./tests/api_tests/tests_de_bridge.py
        env:
          KEYS_DE_BRIDGE: ${{ secrets.KEYS_DE_BRIDGE }}
